// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title  StealthAnnouncer
 * @notice ERC-5564 compliant public announcement registry.
 *         Stores nothing on-chain — only emits events.
 *         Anyone can call announce(); the relayer (or sender) does it on behalf of Alice.
 *
 *  Event layout
 *  ─────────────
 *  schemeId       1  = secp256k1 + sha256  (ERC-5564 scheme 1)
 *  stealthAddr    the freshly-deployed vault that received the ETH
 *  caller         msg.sender  (Alice / her relayer)
 *  ephemeralPubKey  33-byte compressed secp256k1 point R
 *  metadata       viewTag (1 byte) || optional extra payload
 */
contract StealthAnnouncer {

    // ─────────────────────────────────────────────────────────────────────────
    //  Events
    // ─────────────────────────────────────────────────────────────────────────

    event Announcement(
        uint256 indexed schemeId,
        address indexed stealthAddr,
        address indexed caller,
        bytes ephemeralPubKey,
        bytes  metadata
    );

    // ─────────────────────────────────────────────────────────────────────────
    //  External
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * @notice Publish a stealth-payment announcement.
     * @param schemeId       Cryptographic scheme (1 = secp256k1/sha256).
     * @param stealthAddr    Address of the deployed StealthVault.
     * @param ephemeralPubKey  33-byte compressed public key R generated by the sender.
     * @param metadata       First byte MUST be the viewTag; remaining bytes are optional.
     */
    function announce(
        uint256        schemeId,
        address        stealthAddr,
        bytes calldata ephemeralPubKey,
        bytes calldata metadata
    ) external {
        require(ephemeralPubKey.length == 33, "StealthAnnouncer: ephemeral key must be 33 bytes");
        require(metadata.length >= 1,         "StealthAnnouncer: metadata needs at least viewTag");

        emit Announcement(
            schemeId,
            stealthAddr,
            msg.sender,
            ephemeralPubKey,
            metadata
        );
    }
}
